### ISSUE TITLE
2018-01: daily report - Ana

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#29]
## 首页-课程-图 （16：9）
 - [x] 精品套餐： -4
 - [x] 新概念英语:  - 3
 - [x] Sat课程:  - 3
 - [x] 托福课程:  -3

<br>

 - [x] 英文原版必读经典 - 高阶:  -5
 - [x] 英文原版必读经典 - 中阶:  -3
 - [x] 英文原版必读经典 - 初阶:  -3

<br> 

- [x]  英美报刊阅读
- [x]  英美报刊外教精读 - 6

<br> 

 - [x] 英文原版桥梁书 – 苏斯博士
 - [x] 英文原版初章书 – 老鼠记者系列
 - [x] 英文原版初章书 - 神奇书屋系列:  -7

<br> 

 - [x] 美国小学语文课程
 - [x] 其它

**Comment by Anawangqi** [comment]
英美报刊 系列 -6 （张）
